### ISSUE TITLE
DSpace 7 Submission Process doesn't support Curation Tasks (like DSpace 6)

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#2868]
**Is your feature request related to a problem? Please describe.**
In DSpace 6, it was possible to kick off certain Curation Tasks via the Submission process.
See https://github.com/DSpace/DSpace/blob/main/dspace/config/modules/submission-curation.cfg

The main Curation Task which supported this feature was Virus Scan: https://wiki.lyrasis.org/display/DSDOC7x/Virus+Scan+Task

**Describe the solution you'd like**
DSpace 7 should also support curation tasks (like Virus Scan) via the Submission process.  (But, to be clear, DSpace 7 already supports curation tasks via the Admin UI. The only feature missing here is the ability to trigger them via the Submission process.)

**Comment by mwoodiupui** [comment]
Yes, please!

**Comment by mwoodiupui** [comment]
Isn't this addressed by #3157?

**Comment by tdonohue** [comment]
@mwoodiupui : Yes, I think you are correct, that the main Curation Task support has already been added, and that support is part of the **Workflow** not the actual submission process.  I think this ticket can be closed.  We can always reopen later, if we find later issues or gaps

**Comment by tdonohue** [comment]
Reopening, as it sounds like this was only solved for the **workflow process** in #3157.  

It was not fixed in the Submission, see related tickets #8139 and #8169 (which are the same issue reported twice)

This was also initially ranked as ["Tier 4: Medium-Low priority"](https://wiki.lyrasis.org/display/DSPACE/DSpace+Release+7.0+Status#DSpaceRelease7.0Status-Tier4:Medium-LowPriority), so adding it to that board.

**Comment by tdonohue** [comment]
Per today's meeting, assigning to @abollini / 4Science, as they volunteered.  Pulling this onto the 7.5 board

**Comment by tdonohue** [comment]
@abollini : This ticket also doesn't have a PR yet for 7.5.  Should this be moved to 7.6?

**Comment by bram-atmire** [comment]
@abollini Is there a status update regarding this change?

**Comment by tdonohue** [comment]
Unfortunately, this Feature ticket missed our [DSpace 10.0 "Feature PR Merge Deadline"](https://wiki.lyrasis.org/display/DSPACE/DSpace+Release+10.0+Status#DSpaceRelease10.0Status-ReleaseTimeline). As DSpace 10.0 is now under a "Feature Freeze", this ticket will be moved to our 11.0 release board in the hopes of completing this feature in the next release.  If there are any questions, let us know.
